import itertools
import math
from typing import Callable, Iterable, Sequence, Tuple

import numpy as np

def _safe_score(score) -> float:
    if isinstance(score, (int, float, bool, np.number)):
        return float(score)
    if isinstance(score, (list, tuple)) and len(score) > 0:
        return float(score[0])
    return float(score)


def _normalize_to_total(phi: np.ndarray, total_score: float) -> np.ndarray:
    s = float(np.sum(phi))
    if math.isclose(s, 0.0, rel_tol=1e-12, abs_tol=1e-12):
        return np.zeros_like(phi)
    return phi * (total_score / s)


def _apply_clip(phi: np.ndarray, clip_value: float) -> np.ndarray:
    if clip_value is None or clip_value <= 0:
        return phi
    return np.clip(phi, -clip_value, clip_value)


def _compute_shapley_exact(
    num_agents: int,
    coalition_value_fn: Callable[[Iterable[int]], float],
) -> np.ndarray:
    agent_indices = list(range(num_agents))
    factorial_n = math.factorial(num_agents)
    phi = np.zeros(num_agents, dtype=np.float32)
    coalition_cache = {}

    def value_of(coalition_tuple: Tuple[int, ...]) -> float:
        if coalition_tuple not in coalition_cache:
            coalition_cache[coalition_tuple] = _safe_score(coalition_value_fn(coalition_tuple))
        return coalition_cache[coalition_tuple]

    for i in agent_indices:
        others = [a for a in agent_indices if a != i]
        for r in range(len(others) + 1):
            for subset in itertools.combinations(others, r):
                subset = tuple(sorted(subset))
                subset_with_i = tuple(sorted(subset + (i,)))
                weight = (math.factorial(len(subset)) * math.factorial(num_agents - len(subset) - 1)) / factorial_n
                marginal = value_of(subset_with_i) - value_of(subset)
                phi[i] += weight * marginal
    return phi


class RealCoalitionShapleyAllocator:
    """
    Real coalition allocator:
    coalition actions are generated by counterfactual rollout, then valued externally.
    """

    def __init__(self, *, clip_value: float = -1.0):
        self.clip_value = clip_value

    def allocate(
        self,
        *,
        actions: Sequence[str],
        rollout_fn: Callable[[Sequence[int]], Sequence[str]],
        coalition_value_fn: Callable[[Sequence[str], Sequence[int]], float],
        coalition_has_answer_fn: Callable[[Sequence[int]], bool] | None = None,
        total_score_precomputed: float | None = None,
    ) -> tuple[np.ndarray, dict]:
        num_agents = len(actions)
        all_agents = tuple(range(num_agents))

        def coalition_score(coalition_indices: Iterable[int]) -> float:
            coalition_tuple = tuple(sorted(coalition_indices))
            if len(coalition_tuple) == 0:
                return 0.0
            if coalition_has_answer_fn is not None and not coalition_has_answer_fn(coalition_tuple):
                return 0.0
            effective_actions = rollout_fn(coalition_tuple)
            return _safe_score(coalition_value_fn(effective_actions, coalition_tuple))

        total_score = float(total_score_precomputed) if total_score_precomputed is not None else coalition_score(all_agents)
        phi = _compute_shapley_exact(num_agents, coalition_score)
        phi = _normalize_to_total(phi, total_score)
        phi = _apply_clip(phi, self.clip_value).astype(np.float32)

        debug = {
            "allocation_mode": "shapley",
            "shapley_method": "exact",
            "total_score": float(total_score),
            "shapley_sum": float(np.sum(phi)),
            "estimated_value_calls": None,
        }
        return phi, debug
